[Dev 213518] - ios example integrates with backend to generate requestsignature
TrustlyInc/trustly-ios-example pull request #9
Opened 2023-11-30 15:19 UTC by marcosrivereto

2023-11-30 18:11 UTC, andresguedes approved these changes
👍🏽

2023-12-06 03:07 UTC, lukevance requested changes
Looks awesome and ran smoothly! But please see the notes regarding instructions for the user and how this should be a optional feature which the user can enable instead of a requirement.

2023-12-06 03:07 UTC, lukevance commented on TrustlySDKDemoIOS/TrustlyLightboxViewController.swift
> +    let signatureApi = SignatureAPI()
maybe consider "requestSignatureAPI" just to keep the nomenclature consistent?

2023-12-06 03:07 UTC, lukevance commented on TrustlySDKDemoIOS/TrustlyLightboxViewController.swift
> +        self.updateEstablishWithRequestSignature()
👍

2023-12-06 03:07 UTC, lukevance commented on TrustlySDKDemoIOS/TrustlyLightboxViewController.swift
> +                try self.establishData["requestSignature"] = result.get()
I'm not sure that this is the right place, but can you comment out the implementation of signing the request and leave a comment to point to where a user can enable it? It's important that a user can follow two paths:

1. simple quickstart: just run the project with no backend integration and no requestSignature
2. add security: later when they have solved this part, the user may want to revisit the project to understand how to setup requestSignatures

See the [AC here ](https://trustly.atlassian.net/browse/DEV-213518) that mentions "uncommenting" the logic. That may not be the right approach but the user should easily understand how to go from step 1 above to step 2.

2023-12-06 03:07 UTC, lukevance commented on TrustlySDKDemoIOS/Utils/Constants.swift
> +    static let BASE_URL = "https://shop-on-merchant.fly.dev"
Should this instead be "localhost" ? Also maybe leave a comment to explain the connection to the nestjs example app and also please add a note to the ReadMe similar to this one: https://github.com/TrustlyInc/trustly-webview-example/blob/4adbfa6713848502616cac99d493b9ded293972b/react-web-app/README.md#server-side-features

2023-12-06 13:54 UTC, marcosrivereto commented on TrustlySDKDemoIOS/TrustlyLightboxViewController.swift
> +    let signatureApi = SignatureAPI()
👍

2023-12-11 17:22 UTC, marcosrivereto commented on TrustlySDKDemoIOS/Utils/Constants.swift
> +    static let BASE_URL = "https://shop-on-merchant.fly.dev"
Updated with the **_Server Side Feature_** section, and text about what url we should use.

2023-12-11 17:24 UTC, marcosrivereto commented on TrustlySDKDemoIOS/TrustlyLightboxViewController.swift
> +                try self.establishData["requestSignature"] = result.get()
I already commented the code and added some instructions about when the merchant need to use the request signature function, and update the ReadMe file with some instructions too.

2023-12-11 21:43 UTC, andresguedes approved these changes

2023-12-12 20:54 UTC, pedroabdenor approved these changes
👍

2023-12-13 03:25 UTC, lukevance approved these changes
LGTM!

2023-12-13 03:25 UTC, lukevance commented on README.md
> -    - Manually Download
Is this because we no longer want to generate packages?

2023-12-13 03:25 UTC, lukevance commented on README.md
> +As the Trustly Lightbox SDK runs on the client, requests between it and the Trustly API must be secured. Calculate a requestSignature using your Access Key from your server and fetch it from your iOS
Nice 👍

2023-12-13 03:25 UTC, lukevance commented on README.md
> +        /* Uncomment this function only if your merchant setup has the "Extended Security" enable in Admin console, and uncomment the code between the lines
👍

2023-12-13 03:25 UTC, lukevance commented on TrustlySDKDemoIOS/Utils/Constants.swift
> +    static let BASE_URL = "<YOUR BACKEND URL>"
👍

2024-01-03 17:16 UTC, merged